import type { Metadata } from "next";
import { GoogleTagManager } from '@next/third-parties/google';
import BootstrapClient from './components/BootstrapClient';
import '../styles/custom.scss';
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-100">
            <body className={`d-flex flex-column h-100 ${inter.className}`}>
                {children}
                <BootstrapClient />
            </body>
            <GoogleTagManager gtmId="GTM-XYZ" />
        </html>
    );
}
